### ISSUE TITLE
[dglo on 2015-02-06 11:21:06] : pDAQ: StringHub - NullPointerException while removing hit

### ISSUE THREAD

**Issue by dglo** [dglo/daq-request-filler#48]
Run 125997 failed because of a NullPointerException:

stringHub#18 icecube.daq.reqFiller.RequestFiller-Sender#18 ERROR [2015-02-06 02:12:05.6400000000] Saw null data payload in Sender#18
stringHub#18 STDERR-Sender#18 ERROR [2015-02-06 02:12:05.6560000000] Exception in thread "Sender#18" java.lang.NullPointerException
stringHub#18 STDERR-Sender#18 ERROR [2015-02-06 02:12:05.6750000000] at java.util.LinkedList.unlink(LinkedList.java:209)
stringHub#18 STDERR-Sender#18 ERROR [2015-02-06 02:12:05.6770000000] at java.util.LinkedList.remove(LinkedList.java:524)
stringHub#18 STDERR-Sender#18 ERROR [2015-02-06 02:12:05.6780000000] at icecube.daq.reqFiller.RequestFiller$WorkerThread.syncRemove(RequestFiller.java:1238)
stringHub#18 STDERR-Sender#18 ERROR [2015-02-06 02:12:05.6800000000] at icecube.daq.reqFiller.RequestFiller$WorkerThread.getData(RequestFiller.java:895)
stringHub#18 STDERR-Sender#18 ERROR [2015-02-06 02:12:05.6810000000] at icecube.daq.reqFiller.RequestFiller$WorkerThread.run(RequestFiller.java:1029)
stringHub#18 STDERR-Sender#18 ERROR [2015-02-06 02:12:05.6820000000] at java.lang.Thread.run(Thread.java:745)

**Comment by dglo** [comment]
[dglo on 2015-02-06 11:27:04]
svn commit -m"Issue 7231: Catch extremely rare (and mysterious) NullPointerException" src/main/java/icecube/daq/reqFiller/RequestFiller.java
Sending        src/main/java/icecube/daq/reqFiller/RequestFiller.java
Transmitting file data .
Committed revision 15394.
