### ISSUE TITLE
[dglo on 2015-03-16 14:05:05] : pDAQ: Run 126159 died due to a NullPointerException

### ISSUE THREAD

**Issue by dglo** [dglo/daq-request-filler#49]
stringHub#46 STDERR-Sender#46 ERROR [2015-03-16 09:06:11.8410000000] Exception in thread "Sender#46" java.lang.NullPointerException
stringHub#46 STDERR-Sender#46 ERROR [2015-03-16 09:06:11.8440000000] at icecube.daq.reqFiller.RequestFiller$WorkerThread.getData(RequestFiller.java:895)
stringHub#46 STDERR-Sender#46 ERROR [2015-03-16 09:06:11.8460000000] at icecube.daq.reqFiller.RequestFiller$WorkerThread.run(RequestFiller.java:1029)
stringHub#46 STDERR-Sender#46 ERROR [2015-03-16 09:06:11.8470000000] at java.lang.Thread.run(Thread.java:745)

**Comment by dglo** [comment]
[dglo on 2015-03-16 14:12:21]
svn commit -m"Issue 7293: Deal with another mysterious NullPointerException"
Sending        src/main/java/icecube/daq/reqFiller/RequestFiller.java
Transmitting file data .
Committed revision 15475.
